apiVersion: v2
name: fastapi-app
description: A Helm chart for FastAPI DevOps application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - devops
  - kubernetes
maintainers:
  - name: DevOps Team
    email: devops@example.com
sources:
  - https://github.com/your-username/fastapi-devops-project
